/**
 * Roadmap types.
 * Stored as subcollection `students/{id}/roadmaps/{roadmapId}`.
 * The React Flow visualization renders this data structure.
 */
import type { BaseEntity, DifficultyLevel } from './common';

export interface Roadmap extends BaseEntity {
  studentId: string;
  targetRole: string;
  targetRoleId: string;
  title: string;
  description?: string;

  /** Roadmap nodes (skill steps, projects, milestones). */
  nodes: RoadmapNode[];

  /** Edges connecting nodes (dependencies). */
  edges: RoadmapEdge[];

  /** Overall roadmap status. */
  status: 'active' | 'completed' | 'archived';

  /** Estimated total duration. */
  estimatedDuration?: string;

  /** AI-generated or manually created. */
  source: 'manual' | 'ai_generated' | 'system_generated' | 'seeded';
}

export type RoadmapNodeType =
  | 'goal'
  | 'skill'
  | 'learning'
  | 'assessment'
  | 'project'
  | 'certification'
  | 'industry_mission'
  | 'mentorship'
  | 'internship'
  | 'job'
  | 'milestone'
  | 'outcome';

export type RoadmapNodeStatus =
  | 'verified'
  | 'in_progress'
  | 'recommended'
  | 'critical_gap'
  | 'locked'
  | 'unlocked'
  | 'completed';

export interface RoadmapNode {
  id: string;
  type: RoadmapNodeType;
  title: string;
  description?: string;
  meta: string; // subtitle text for display

  /** Current status of this node. */
  status: RoadmapNodeStatus;

  /** Skills this node develops or requires. */
  skills?: string[];

  /** Estimated duration. */
  duration?: string;
  difficulty?: DifficultyLevel;

  /** Evidence generated by completing this node. */
  evidenceType?: string;

  /** Dependencies (ids of nodes that must be completed first). */
  dependencies?: string[];

  /** Resources and links. */
  resources?: RoadmapResource[];

  /** Position for React Flow rendering. */
  position: { x: number; y: number };

  /** Additional metadata. */
  metadata?: Record<string, unknown>;
}

export interface RoadmapEdge {
  id: string;
  source: string;
  target: string;
  animated?: boolean;
  label?: string;
}

export interface RoadmapResource {
  title: string;
  url: string;
  type: 'video' | 'article' | 'course' | 'documentation' | 'project';
}
